import './build.mjs';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
const catalog=JSON.parse(await readFile('frontend/data/catalog.json','utf8'));
const reference=JSON.parse(await readFile('frontend/data/reference.json','utf8'));
const root='https://juldigi0107.github.io/hogwarts-indonesia/';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shell=(title,description,canonical,body,type='CollectionPage')=>`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — Hogwarts Indonesia</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(title)} — Hogwarts Indonesia"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="stylesheet" href="../css/tokens.css"><link rel="stylesheet" href="../css/base.css"><link rel="stylesheet" href="../css/components.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':type,name:title,url:canonical,description})}</script></head><body><main style="max-width:980px;margin:auto;padding:4rem 6vw"><p class="eyebrow">Hogwarts Indonesia</p>${body}<p><a class="button" href="../#/${canonical.replace(root,'').replace(/\/$/,'')}">Buka versi interaktif</a></p></main></body></html>`;
const urls=[root,...catalog.articles.map(a=>root+'artikel/'+a.slug+'/')];
for(const c of catalog.categories){const list=catalog.articles.filter(a=>a.category===c.slug);const dir='dist/'+c.slug;await mkdir(dir,{recursive:true});const canonical=root+c.slug+'/';urls.push(canonical);const body=`<h1>${esc(c.title)}</h1><p>${esc(c.subtitle)}</p><ul>${list.map(a=>`<li><a href="../artikel/${esc(a.slug)}/">${esc(a.title)}</a> — ${esc(a.intro)}</li>`).join('')}</ul>`;await writeFile(dir+'/index.html',shell(c.title,`Koleksi ${c.title} dalam ensiklopedia Hogwarts Indonesia.`,canonical,body))}
const timelineBody=`<h1>Timeline Dunia Sihir</h1><p>Urutan editorial peristiwa. Label relatif digunakan ketika tanggal absolut tidak aman untuk dinyatakan.</p><ol>${(reference.timeline||[]).map(e=>`<li><strong>${esc(e.year_label||e.era||'Era')}</strong> — ${esc(e.title)}. ${esc(e.summary)}</li>`).join('')}</ol>`;
const glossaryBody=`<h1>Glosarium</h1><dl>${(reference.glossary||[]).map(x=>`<dt><strong>${esc(x.term)}</strong></dt><dd>${esc(x.definition)}</dd>`).join('')}</dl>`;
const mapBody='<h1>Peta Kastil</h1><p>Peta Hogwarts Indonesia adalah navigasi ilustratif editorial dan tidak mengklaim sebagai denah canon atau koordinat resmi.</p><img src="../assets/generated/castle-map.svg" alt="Peta ilustratif kastil Hogwarts Indonesia">';
const staticPages=[['timeline','Timeline Dunia Sihir','Urutan editorial peristiwa dunia sihir.',timelineBody],['glosarium','Glosarium','Istilah penting dunia sihir dalam Bahasa Indonesia.',glossaryBody],['peta','Peta Kastil','Peta ilustratif untuk navigasi arsip.',mapBody],['tentang','Tentang Hogwarts Indonesia','Tentang proyek ensiklopedis fan-made independen.','<h1>Tentang Hogwarts Indonesia</h1><p>Proyek ensiklopedis fan-made independen berbahasa Indonesia. Nama ini adalah identitas antarmuka dan bukan klaim adanya sekolah Hogwarts resmi di Indonesia.</p>'],['sumber','Sumber & Provenance','Catatan sumber dan provenance riset.','<h1>Sumber & Provenance</h1><p>Narasi ditulis ulang secara transformatif dan fakta penting ditautkan ke sumber riset. File visual resmi tidak otomatis disalin.</p>'],['kredit-aset','Kredit Aset','Provenance aset visual Hogwarts Indonesia.','<h1>Kredit Aset</h1><p>Aset generated dan internet dicatat di assets-manifest.json. Aset internet hanya diterbitkan setelah audit lisensi.</p>']];
for(const [slug,title,description,body] of staticPages){await mkdir('dist/'+slug,{recursive:true});const canonical=root+slug+'/';urls.push(canonical);await writeFile(`dist/${slug}/index.html`,shell(title,description,canonical,body))}
await mkdir('dist/astronomi',{recursive:true});urls.push(root+'astronomi/');await writeFile('dist/astronomi/index.html',shell('Astronomi','Arsip astronomi dan Astronomy Tower.',root+'astronomi/',`<h1>Astronomi</h1><ul><li>Astronomy — studi bintang, bulan, planet, dan star chart.</li><li>Astronomy Tower — ruang observasi dan pembelajaran di Hogwarts.</li></ul>`));
await writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[...new Set(urls)].map(u=>`<url><loc>${u}</loc></url>`).join('')+'</urlset>');
console.log(`Enhanced build: ${catalog.categories.length} collections, ${catalog.articles.length} articles, ${urls.length} sitemap URLs.`);
