import './build.mjs';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
const load=async path=>JSON.parse(await readFile(path,'utf8'));
const [catalog,reference,characterScale,creatureScale,spellScale,astronomy]=await Promise.all([
  load('frontend/data/catalog.json'),load('frontend/data/reference.json'),load('frontend/data/reference-scale.json'),load('frontend/data/creatures-scale.json'),load('frontend/data/spells-scale.json'),load('frontend/data/astronomy.json')
]);
const root='https://juldigi0107.github.io/hogwarts-indonesia/';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mergeUnique=(base=[],extra=[])=>{const map=new Map();for(const item of [...base,...extra])if(item?.slug)map.set(item.slug,item);return [...map.values()]};
const characters=mergeUnique(reference.characters,characterScale.items),creatures=mergeUnique(reference.creatures,creatureScale.items),spells=mergeUnique(reference.spells,spellScale.items);
const shell=(title,description,canonical,body,type='CollectionPage',interactivePath='')=>`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — Hogwarts Indonesia</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(title)} — Hogwarts Indonesia"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="stylesheet" href="${root}css/tokens.css"><link rel="stylesheet" href="${root}css/base.css"><link rel="stylesheet" href="${root}css/components.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':type,name:title,url:canonical,description})}</script></head><body><main style="max-width:980px;margin:auto;padding:4rem 6vw"><p class="eyebrow">Hogwarts Indonesia</p>${body}<p><a class="button" href="${root}#${interactivePath||'/'}">Buka versi interaktif</a></p></main></body></html>`;
const urls=[root,...catalog.articles.map(a=>root+'artikel/'+a.slug+'/')];
for(const c of catalog.categories){const list=catalog.articles.filter(a=>a.category===c.slug);const dir='dist/'+c.slug;await mkdir(dir,{recursive:true});const canonical=root+c.slug+'/';urls.push(canonical);const body=`<h1>${esc(c.title)}</h1><p>${esc(c.subtitle)}</p><ul>${list.map(a=>`<li><a href="${root}artikel/${esc(a.slug)}/">${esc(a.title)}</a> — ${esc(a.intro)}</li>`).join('')}</ul>`;await writeFile(dir+'/index.html',shell(c.title,`Koleksi ${c.title} dalam ensiklopedia Hogwarts Indonesia.`,canonical,body,'CollectionPage','/'+c.slug))}
const entityBody=(title,intro,items,details,baseSlug='')=>`<h1>${esc(title)}</h1><p>${esc(intro)}</p><p><strong>${items.length}</strong> entri tersedia pada build ini.</p><ol>${items.map(x=>{const label=x.name||x.title||x.term;return `<li><article><h2>${baseSlug&&x.slug?`<a href="${root}${baseSlug}/${esc(x.slug)}/">${esc(label)}</a>`:esc(label)}</h2><p>${esc(x.summary||x.description||x.purpose||x.definition||'')}</p>${details(x)}</article></li>`}).join('')}</ol>`;
const provenanceBlock=source=>source?.url?`<aside><h2>Provenance</h2><p>Sumber tingkat batch: <a href="${esc(source.url)}" rel="noopener noreferrer">${esc(source.title||source.publisher||'Sumber resmi')}</a>. Ringkasan ditulis ulang secara transformatif; direct source per entri tetap diperkaya melalui CMS.</p></aside>`:'';
const writeEntityDetails=async({baseSlug,interactiveBase,sectionTitle,items,details,source=null})=>{for(const x of items){if(!x.slug)continue;const label=x.name||x.title||x.term||x.slug,summary=x.summary||x.description||x.purpose||x.definition||'',dir=`dist/${baseSlug}/${x.slug}`,canonical=`${root}${baseSlug}/${x.slug}/`;await mkdir(dir,{recursive:true});urls.push(canonical);const body=`<nav><a href="${root}${baseSlug}/">← ${esc(sectionTitle)}</a></nav><article><p class="eyebrow">${esc(x.classification||x.type||x.house||sectionTitle)}</p><h1>${esc(label)}</h1><p><strong>${esc(summary)}</strong></p>${details(x)}${x.safety_note?`<aside><h2>Catatan keselamatan</h2><p>${esc(x.safety_note)}</p></aside>`:''}${provenanceBlock(source)}</article>`;await writeFile(`${dir}/index.html`,shell(label,summary||`${label} dalam ensiklopedia Hogwarts Indonesia.`,canonical,body,'Article',`${interactiveBase}/${x.slug}`))}}
const entityPages=[
  {slug:'tokoh',title:'Tokoh',description:'Indeks tokoh dunia sihir dalam Bahasa Indonesia.',items:characters,path:'/tokoh',source:characterScale.source,details:x=>`<p>${x.house?`Asrama: ${esc(x.house)}. `:''}${x.affiliation?`Afiliasi: ${esc(x.affiliation)}.`:''}</p>`},
  {slug:'makhluk',title:'Makhluk Sihir',description:'Field guide makhluk, klasifikasi, habitat, dan risiko.',items:creatures,path:'/makhluk',source:creatureScale.source,details:x=>`<p>Klasifikasi: ${esc(x.classification||'—')}. Habitat: ${esc(x.habitat||'—')}. Risiko: ${esc(x.danger_level||'—')}.</p>`},
  {slug:'lokasi',title:'Lokasi Ikonik',description:'Lokasi penting dan konteksnya dalam dunia sihir.',items:reference.locations||[],path:'/lokasi',details:x=>`<p>Wilayah: ${esc(x.region||'—')}.</p>`},
  {slug:'herbologi',title:'Herbologi',description:'Tanaman sihir, habitat, dan konteks lore.',items:reference.plants||[],path:'/herbologi',details:x=>`<p>Habitat: ${esc(x.habitat||'—')}.</p>`},
  {slug:'astronomi',title:'Astronomi',description:'Astronomy Tower, star chart, planet, dan observasi langit.',items:astronomy.items||[],path:'/astronomi',source:astronomy.sources?.[0],details:x=>`<p>Jenis: ${esc(x.type||'Astronomi')}.</p>`}
];
for(const page of entityPages){await mkdir('dist/'+page.slug,{recursive:true});const canonical=root+page.slug+'/';urls.push(canonical);await writeFile(`dist/${page.slug}/index.html`,shell(page.title,page.description,canonical,entityBody(page.title,page.description,page.items,page.details,page.slug),'CollectionPage',page.path));await writeEntityDetails({baseSlug:page.slug,interactiveBase:page.path,sectionTitle:page.title,items:page.items,details:page.details,source:page.source})}
await mkdir('dist/grimoire',{recursive:true});await mkdir('dist/grimoire/mantra',{recursive:true});await mkdir('dist/grimoire/ramuan',{recursive:true});await mkdir('dist/grimoire/artefak',{recursive:true});
urls.push(root+'grimoire/',root+'grimoire/mantra/',root+'grimoire/ramuan/',root+'grimoire/artefak/');
await writeFile('dist/grimoire/index.html',shell('Grimoire','Mantra, ramuan, dan artefak dalam satu indeks.',root+'grimoire/',`<h1>Grimoire</h1><ul><li><a href="${root}grimoire/mantra/">${spells.length} mantra</a></li><li><a href="${root}grimoire/ramuan/">${(reference.potions||[]).length} ramuan utama</a></li><li><a href="${root}grimoire/artefak/">${(reference.artifacts||[]).length} artefak utama</a></li></ul>`,'CollectionPage','/grimoire'));
const spellDetails=x=>`<p>Pelafalan: ${esc(x.incantation||'—')}. Jenis: ${esc(x.type||'—')}. Kesulitan: ${esc(x.difficulty||'—')}. Status: ${esc(x.legal_status||'—')}.</p>`;
const potionDetails=x=>`<p>Jenis: ${esc(x.type||'—')}.</p>`;
const artifactDetails=x=>`<p>Jenis: ${esc(x.type||'—')}.</p>`;
await writeFile('dist/grimoire/mantra/index.html',shell('Mantra','Indeks mantra, pelafalan, fungsi, tingkat kesulitan, dan status legal dalam lore.',root+'grimoire/mantra/',entityBody('Mantra','Mantra adalah unsur fiksi dalam ensiklopedia ini.',spells,spellDetails,'grimoire/mantra'),'CollectionPage','/grimoire/mantra'));
await writeFile('dist/grimoire/ramuan/index.html',shell('Ramuan','Arsip ramuan dalam lore; bukan instruksi praktik dunia nyata.',root+'grimoire/ramuan/',entityBody('Ramuan','Informasi berikut adalah konteks fiksi dan bukan petunjuk konsumsi atau medis.',reference.potions||[],potionDetails,'grimoire/ramuan'),'CollectionPage','/grimoire/ramuan'));
await writeFile('dist/grimoire/artefak/index.html',shell('Artefak','Benda sihir dan perannya dalam peristiwa penting.',root+'grimoire/artefak/',entityBody('Artefak','Indeks benda sihir utama.',reference.artifacts||[],artifactDetails,'grimoire/artefak'),'CollectionPage','/grimoire/artefak'));
await writeEntityDetails({baseSlug:'grimoire/mantra',interactiveBase:'/grimoire/mantra',sectionTitle:'Mantra',items:spells,details:spellDetails,source:spellScale.source});
await writeEntityDetails({baseSlug:'grimoire/ramuan',interactiveBase:'/grimoire/ramuan',sectionTitle:'Ramuan',items:reference.potions||[],details:potionDetails});
await writeEntityDetails({baseSlug:'grimoire/artefak',interactiveBase:'/grimoire/artefak',sectionTitle:'Artefak',items:reference.artifacts||[],details:artifactDetails});
const timelineBody=`<h1>Timeline Dunia Sihir</h1><p>Urutan editorial peristiwa. Label relatif digunakan ketika tanggal absolut tidak aman untuk dinyatakan.</p><ol>${(reference.timeline||[]).map(e=>`<li><strong>${esc(e.year_label||e.era||'Era')}</strong> — ${esc(e.title)}. ${esc(e.summary)}</li>`).join('')}</ol>`;
const glossaryBody=`<h1>Glosarium</h1><dl>${(reference.glossary||[]).map(x=>`<dt><strong>${esc(x.term)}</strong></dt><dd>${esc(x.definition)}</dd>`).join('')}</dl>`;
const mapBody='<h1>Peta Kastil</h1><p>Peta Hogwarts Indonesia adalah navigasi ilustratif editorial dan tidak mengklaim sebagai denah canon atau koordinat resmi.</p><img src="'+root+'assets/generated/castle-map.svg" alt="Peta ilustratif kastil Hogwarts Indonesia">';
const staticPages=[['timeline','Timeline Dunia Sihir','Urutan editorial peristiwa dunia sihir.',timelineBody],['glosarium','Glosarium','Istilah penting dunia sihir dalam Bahasa Indonesia.',glossaryBody],['peta','Peta Kastil','Peta ilustratif untuk navigasi arsip.',mapBody],['tentang','Tentang Hogwarts Indonesia','Tentang proyek ensiklopedis fan-made independen.','<h1>Tentang Hogwarts Indonesia</h1><p>Proyek ensiklopedis fan-made independen berbahasa Indonesia. Nama ini adalah identitas antarmuka dan bukan klaim adanya sekolah Hogwarts resmi di Indonesia.</p>'],['sumber','Sumber & Provenance','Catatan sumber dan provenance riset.','<h1>Sumber & Provenance</h1><p>Narasi ditulis ulang secara transformatif dan fakta penting ditautkan ke sumber riset. Dataset skala memakai official Fact Files index sebagai provenance tingkat batch sambil menunggu enrichment URL per entri.</p>'],['kredit-aset','Kredit Aset','Provenance aset visual Hogwarts Indonesia.','<h1>Kredit Aset</h1><p>Aset generated dan internet dicatat di assets-manifest.json. Aset internet hanya diterbitkan setelah audit lisensi.</p>']];
for(const [slug,title,description,body] of staticPages){await mkdir('dist/'+slug,{recursive:true});const canonical=root+slug+'/';urls.push(canonical);await writeFile(`dist/${slug}/index.html`,shell(title,description,canonical,body,'CollectionPage','/'+slug))}
await writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[...new Set(urls)].map(u=>`<url><loc>${u}</loc></url>`).join('')+'</urlset>');
console.log(`Enhanced build: ${catalog.categories.length} collections, ${catalog.articles.length} articles, ${characters.length} characters, ${creatures.length} creatures, ${spells.length} spells, ${new Set(urls).size} sitemap URLs.`);
