import {readFile,mkdir,writeFile,cp} from 'node:fs/promises';
const data=JSON.parse(await readFile('frontend/data/catalog.json','utf8'));
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
await mkdir('dist',{recursive:true});await cp('frontend','dist',{recursive:true});
const root='https://juldigi0107.github.io/hogwarts-indonesia/';
let urls=[root];
await mkdir('dist/artikel',{recursive:true});
for(const a of data.articles){const url=root+'artikel/'+a.slug+'/';urls.push(url);await mkdir('dist/artikel/'+a.slug,{recursive:true});await writeFile('dist/artikel/'+a.slug+'/index.html','<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escape(a.title)+' — Hogwarts Indonesia</title><meta name="description" content="'+escape(a.intro)+'"><link rel="canonical" href="'+url+'"><meta property="og:title" content="'+escape(a.title)+'"><meta property="og:description" content="'+escape(a.intro)+'"><meta property="og:type" content="article"><link rel="stylesheet" href="../../css/app.css"></head><body><main><a href="../../#/index">← Perpustakaan</a><article class="folio"><h1>'+escape(a.title)+'</h1><p>'+escape(a.intro)+'</p>'+a.sections.map(s=>'<h2>'+escape(s.heading)+'</h2><p>'+escape(s.text)+'</p>').join('')+'<aside>'+escape(a.note)+'</aside><h2>Sumber</h2><p>'+escape(a.source.title)+' '+escape(a.source.locator||'')+'</p>'+(a.source.url?'<p><a href="'+escape(a.source.url)+'">Buka sumber resmi</a></p>':'')+'<p>'+escape(a.source.verification)+'</p></article><a href="../../#/artikel/'+a.slug+'">Buka versi interaktif</a></main></body></html>')}
await writeFile('dist/artikel/index.html','<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Indeks — Hogwarts Indonesia</title><link rel="stylesheet" href="../css/app.css"><main><h1>Indeks artikel</h1><ul>'+data.articles.map(a=>'<li><a href="./'+a.slug+'/">'+escape(a.title)+'</a></li>').join('')+'</ul><a href="../">Beranda</a></main></html>');
await writeFile('dist/404.html','<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Halaman tidak ditemukan</title><main><h1>Lorong ini tidak ditemukan.</h1><a href="/hogwarts-indonesia/">Kembali ke perpustakaan</a></main></html>');
await writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>'<url><loc>'+u+'</loc></url>').join('')+'</urlset>');
await writeFile('dist/robots.txt','User-agent: *\nAllow: /\nSitemap: '+root+'sitemap.xml\n');
await writeFile('dist/.nojekyll','');console.log('Built '+data.articles.length+' article pages.');
