import {readFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
const required=['dist/index.html','dist/offline.html','dist/admin.html','dist/peta/index.html','dist/timeline/index.html','dist/glosarium/index.html','dist/relasi/index.html','dist/astronomi/index.html','dist/tokoh/index.html','dist/tokoh/harry-potter/index.html','dist/makhluk/index.html','dist/makhluk/dementor/index.html','dist/herbologi/index.html','dist/lokasi/index.html','dist/grimoire/index.html','dist/grimoire/mantra/index.html','dist/grimoire/mantra/expecto-patronum/index.html','dist/grimoire/ramuan/index.html','dist/grimoire/artefak/index.html','dist/assets/generated/castle-entry.svg','dist/assets/generated/castle-map.svg','dist/data/catalog.json','dist/data/reference.json','dist/data/reference-scale.json','dist/data/creatures-scale.json','dist/data/spells-scale.json','dist/data/exploration.json','dist/data/astronomy.json','dist/data/relationships.json','dist/js/app-v2.js','dist/js/pages-graph.js','dist/css/graph.css','dist/css/deep-dive.css','dist/service-worker.js','dist/sitemap.xml','dist/robots.txt'];
const missing=required.filter(p=>!existsSync(p));if(missing.length)throw new Error('Missing build files: '+missing.join(', '));
const sitemap=await readFile('dist/sitemap.xml','utf8');for(const path of ['/hogwarts/','/peta/','/timeline/','/glosarium/','/relasi/','/astronomi/','/tokoh/','/tokoh/harry-potter/','/makhluk/','/makhluk/dementor/','/herbologi/','/lokasi/','/grimoire/','/grimoire/mantra/','/grimoire/mantra/expecto-patronum/','/grimoire/ramuan/','/grimoire/artefak/']){if(!sitemap.includes('https://juldigi0107.github.io/hogwarts-indonesia'+path))throw new Error('Sitemap missing '+path)}
const sw=await readFile('dist/service-worker.js','utf8');for(const asset of ['pages-graph.js','relationships.json','castle-map.svg','reference-scale.json','creatures-scale.json','spells-scale.json','exploration.json','deep-dive.css'])if(!sw.includes(asset))throw new Error('Service worker core missing '+asset);
const catalog=JSON.parse(await readFile('dist/data/catalog.json','utf8'));for(const a of catalog.articles){if(!existsSync(`dist/artikel/${a.slug}/index.html`))throw new Error('Missing article route '+a.slug)}
const characterScale=JSON.parse(await readFile('dist/data/reference-scale.json','utf8')),creatureScale=JSON.parse(await readFile('dist/data/creatures-scale.json','utf8')),spellScale=JSON.parse(await readFile('dist/data/spells-scale.json','utf8'));
if((characterScale.items||[]).length<100)throw new Error('Built character scale below target');
if((creatureScale.items||[]).length<50)throw new Error('Built creature scale below target');
if((spellScale.items||[]).length<70)throw new Error('Built spell scale below target');
const checks=[['dist/tokoh/index.html','Harry Potter'],['dist/tokoh/harry-potter/index.html','Dumbledore'],['dist/makhluk/index.html','Dementor'],['dist/makhluk/dementor/index.html','Azkaban'],['dist/grimoire/mantra/index.html','Expecto Patronum'],['dist/grimoire/mantra/expecto-patronum/index.html','Patronus']];
for(const [file,needle] of checks){const html=await readFile(file,'utf8');if(!html.includes(needle))throw new Error(`${file} missing representative content: ${needle}`)}
console.log(`Build validation passed: ${catalog.categories.length} collections, ${catalog.articles.length} article pages, ${characterScale.items.length} character seeds, ${creatureScale.items.length} creature seeds, ${spellScale.items.length} spell seeds, crawlable entity details, relationship graph and exploration routes present.`);
