const $=s=>document.querySelector(s);let base='',token='',items=[];
const api=async(path,options={})=>{const res=await fetch(base+path,{...options,headers:{Accept:'application/json',Authorization:'Bearer '+token,...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});let data={};try{data=await res.json()}catch{}if(!res.ok){const error=new Error(data?.error?.code||'HTTP_'+res.status);error.status=res.status;throw error}return data};
const setStatus=(text,ok=false)=>{$('#api-status').textContent=text;$('#api-dot').classList.toggle('ok',ok)};const setNotice=t=>$('#editor-notice').textContent=t;
function metrics(){const docs=items.map(x=>{try{return JSON.parse(x.document)}catch{return{}}});$('#metric-content').textContent=items.length;$('#metric-draft').textContent=items.filter(x=>x.status==='draft').length;$('#metric-published').textContent=items.filter(x=>x.status==='published').length;$('#metric-source').textContent=docs.filter(x=>x.source?.title).length}
function renderList(){const root=$('#content-list');if(!items.length){root.innerHTML='<p>Belum ada record konten.</p>';metrics();return}root.innerHTML=items.map(row=>`<article class="content-row"><div><h3>${escapeHtml(row.title)}</h3><p>${escapeHtml(row.slug)} · revisi ${Number(row.revision)||1} · <span class="badge">${escapeHtml(row.status)}</span></p></div><button class="button" data-edit="${Number(row.id)}">Edit</button></article>`).join('');root.querySelectorAll('[data-edit]').forEach(btn=>btn.addEventListener('click',()=>openEditor(Number(btn.dataset.edit))));metrics()}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(){try{const data=await api('/api/v1/admin/content');items=data.items||[];renderList();setStatus('API terhubung',true);$('#refresh').disabled=false;$('#new-content').disabled=false}catch(error){setStatus('Gagal: '+error.message,false);$('#content-list').innerHTML='<p>Tidak dapat memuat konten. Periksa Worker, CORS, binding, dan token.</p>'}}
function openEditor(id=null){const form=$('#content-form');form.reset();$('#editor').classList.remove('hidden');$('#delete-content').classList.toggle('hidden',!id);$('#content-id').value=id||'';$('#content-revision').value='';if(!id){$('#editor-title').textContent='Artikel baru';setNotice('');location.hash='editor';return}const row=items.find(x=>Number(x.id)===id);if(!row)return;let doc={};try{doc=JSON.parse(row.document)}catch{}$('#editor-title').textContent='Edit: '+row.title;form.slug.value=row.slug||doc.slug||'';form.category.value=row.category||doc.category||'';form.title.value=row.title||doc.title||'';form.intro.value=row.intro||doc.intro||'';form.body.value=doc.sections?.[0]?.text||'';form.source_title.value=doc.source?.title||'';form.source_url.value=doc.source?.url||'';form.note.value=doc.note||'';form.status.value=row.status||doc.status||'draft';$('#content-revision').value=row.revision||1;setNotice('Revisi '+(row.revision||1));location.hash='editor'}
function payload(){const f=$('#content-form');return{slug:f.slug.value.trim(),category:f.category.value.trim(),title:f.title.value.trim(),intro:f.intro.value.trim(),sections:[{heading:'Artikel utama',text:f.body.value.trim()}],source:{title:f.source_title.value.trim(),url:f.source_url.value.trim()||null,verification:'Dikelola melalui Editorial Console'},note:f.note.value.trim(),related:[],status:f.status.value}}
$('#connect').addEventListener('click',async()=>{base=$('#api-base').value.trim().replace(/\/$/,'');token=$('#admin-token').value;if(!/^https?:\/\//.test(base)||token.length<32){setStatus('URL atau token belum valid');return}try{const health=await fetch(base+'/api/v1/health').then(r=>r.json());if(health.status!=='ok')throw new Error('HEALTH_CHECK');await load()}catch{setStatus('Worker belum dapat diverifikasi')}});
$('#refresh').addEventListener('click',load);$('#new-content').addEventListener('click',()=>openEditor());$('#cancel-edit').addEventListener('click',()=>{$('#editor').classList.add('hidden');location.hash='content'});
$('#content-form').addEventListener('submit',async event=>{event.preventDefault();const id=Number($('#content-id').value)||null,revision=Number($('#content-revision').value)||null,body=payload();setNotice('Menyimpan…');try{const data=id?await api('/api/v1/admin/content/'+id,{method:'PUT',headers:{'If-Match':String(revision)},body:JSON.stringify(body)}):await api('/api/v1/admin/content',{method:'POST',body:JSON.stringify(body)});setNotice('Tersimpan. Revisi '+(data.revision||1));await load();if(data.id)openEditor(Number(data.id))}catch(error){setNotice('Gagal: '+error.message)}});
$('#delete-content').addEventListener('click',async()=>{const id=Number($('#content-id').value),revision=Number($('#content-revision').value);if(!id||!revision)return;if(!confirm('Soft-delete artikel ini? Record tetap dapat diaudit di database.'))return;setNotice('Menghapus…');try{await api('/api/v1/admin/content/'+id,{method:'DELETE',headers:{'If-Match':String(revision)}});$('#editor').classList.add('hidden');await load();location.hash='content'}catch(error){setNotice('Gagal: '+error.message)}});
