const timeout=ms=>new Promise((_,reject)=>setTimeout(()=>reject(new Error('TIMEOUT')),ms));
const json=async(url,options={})=>{const res=await Promise.race([fetch(url,{...options,headers:{Accept:'application/json',...(options.headers||{})}}),timeout(7000)]);if(!res.ok){const e=new Error('HTTP_'+res.status);e.status=res.status;throw e}return res.json()};
const normalize=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();
const searchableText=item=>normalize([item.title,item.name,item.term,item.slug,item.intro,item.summary,item.definition,item.purpose,item.description,item.house,item.affiliation,item.habitat,item.classification,item.region,item.type,item.incantation,item.difficulty,item.legal_status,item.danger_level].filter(Boolean).join(' '));
function editDistance(a,b){a=normalize(a);b=normalize(b);if(!a)return b.length;if(!b)return a.length;const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old}}return row[b.length]}
function looseMatch(text,term){if(!term)return true;const hay=normalize(text),needle=normalize(term);if(hay.includes(needle))return true;if(needle.length<4)return false;return hay.split(/\s+/).some(word=>Math.abs(word.length-needle.length)<=2&&editDistance(word,needle)<=Math.max(1,Math.floor(needle.length/4)))}
function mergeUnique(base=[],extra=[],key='slug'){const map=new Map();for(const item of [...base,...extra]){const id=item?.[key]||item?.name||item?.term;if(id)map.set(String(id),item)}return [...map.values()]}

export function createApi({apiBase='',catalogUrl}){
  const base=(apiBase||'').replace(/\/$/,'');
  const referenceUrl=new URL('../data/reference.json',import.meta.url),astronomyUrl=new URL('../data/astronomy.json',import.meta.url),explorationUrl=new URL('../data/exploration.json',import.meta.url),characterScaleUrl=new URL('../data/reference-scale.json',import.meta.url),creatureScaleUrl=new URL('../data/creatures-scale.json',import.meta.url),spellScaleUrl=new URL('../data/spells-scale.json',import.meta.url);
  let catalogPromise=null,referencePromise=null,astronomyPromise=null,explorationPromise=null,characterScalePromise=null,creatureScalePromise=null,spellScalePromise=null,expandedReferencePromise=null;
  const catalog=()=>catalogPromise||(catalogPromise=json(catalogUrl));
  const reference=()=>referencePromise||(referencePromise=json(referenceUrl));
  const astronomy=()=>astronomyPromise||(astronomyPromise=json(astronomyUrl));
  const exploration=()=>explorationPromise||(explorationPromise=json(explorationUrl));
  const characterScale=()=>characterScalePromise||(characterScalePromise=json(characterScaleUrl));
  const creatureScale=()=>creatureScalePromise||(creatureScalePromise=json(creatureScaleUrl));
  const spellScale=()=>spellScalePromise||(spellScalePromise=json(spellScaleUrl));
  const expandedReference=()=>expandedReferencePromise||(expandedReferencePromise=Promise.all([reference(),characterScale(),creatureScale(),spellScale()]).then(([ref,chars,creatures,spells])=>({...ref,characters:mergeUnique(ref.characters,chars.items),creatures:mergeUnique(ref.creatures,creatures.items),spells:mergeUnique(ref.spells,spells.items),scaleSources:[chars.source,creatures.source,spells.source].filter(Boolean)})));
  const fallback=async kind=>{if(kind==='categories'){const d=await catalog();return{items:d.categories||[]}}if(kind==='content'){const d=await catalog();return{items:d.articles||[]}}if(kind==='astronomy')return astronomy();if(kind==='mapNodes'||kind==='dailyFeatures'){const d=await exploration();return{items:d[kind]||[]}}const d=await expandedReference();return{items:d[kind]||[],sources:d.scaleSources||[]}};
  const get=async(path,kind)=>{if(base){try{return await json(base+path)}catch(error){console.warn('[Hogwarts Indonesia] API fallback',path,error.message)}}return fallback(kind)};
  const localSearch=async(params={})=>{const term=normalize(params.q||''),type=normalize(params.type||''),category=normalize(params.category||'');const [cat,ref,astro]=await Promise.all([catalog(),expandedReference(),astronomy()]);const groups={article:(cat.articles||[]).map(x=>({...x,entityType:'article',label:x.title,description:x.intro,route:'/artikel/'+x.slug})),character:(ref.characters||[]).map(x=>({...x,entityType:'character',label:x.name,description:x.summary,route:'/tokoh?q='+encodeURIComponent(x.name)})),creature:(ref.creatures||[]).map(x=>({...x,entityType:'creature',label:x.name,description:x.summary,route:'/makhluk?q='+encodeURIComponent(x.name)})),spell:(ref.spells||[]).map(x=>({...x,entityType:'spell',label:x.incantation||x.name,description:x.purpose,route:'/grimoire/mantra?q='+encodeURIComponent(x.incantation||x.name)})),potion:(ref.potions||[]).map(x=>({...x,entityType:'potion',label:x.name,description:x.purpose,route:'/grimoire/ramuan?q='+encodeURIComponent(x.name)})),artifact:(ref.artifacts||[]).map(x=>({...x,entityType:'artifact',label:x.name,description:x.summary,route:'/grimoire/artefak?q='+encodeURIComponent(x.name)})),location:(ref.locations||[]).map(x=>({...x,entityType:'location',label:x.name,description:x.summary,route:'/lokasi?q='+encodeURIComponent(x.name)})),glossary:(ref.glossary||[]).map(x=>({...x,entityType:'glossary',label:x.term,description:x.definition,route:'/glosarium?q='+encodeURIComponent(x.term)})),astronomy:(astro.items||[]).map(x=>({...x,entityType:'astronomy',label:x.name,description:x.summary,route:'/astronomi?q='+encodeURIComponent(x.name)}))};let items=Object.values(groups).flat();if(type)items=items.filter(x=>normalize(x.entityType)===type);if(category)items=items.filter(x=>x.entityType!=='article'||normalize(x.category)===category);if(term)items=items.filter(x=>looseMatch(searchableText(x),term));return{items:items.slice(0,100),total:items.length,mode:'static-fallback',source:'expanded-reference'}};
  const normalizeDaily=response=>{const rows=response?.items||[];return{...response,items:rows.map(row=>{if(row.title||row.summary||row.route)return row;const type=row.feature_type||row.type||'fact',route=type==='creature'?'/makhluk':type==='spell'?'/grimoire/mantra':type==='artifact'?'/grimoire/artefak':'/index';return{type,title:row.headline||'Catatan hari ini',summary:row.note||'',route}})}};
  return{health:()=>base?json(base+'/api/v1/health'):Promise.resolve({status:'static-fallback'}),categories:()=>get('/api/v1/categories','categories'),content:(params={})=>{const q=new URLSearchParams(params);return get('/api/v1/content'+(q.size?'?'+q:''),'content')},contentBySlug:async slug=>{if(base){try{return await json(base+'/api/v1/content/'+encodeURIComponent(slug))}catch(error){console.warn('[Hogwarts Indonesia] detail fallback',error.message)}}const d=await catalog();return d.articles?.find(x=>x.slug===slug)||null},entities:kind=>get('/api/v1/'+kind,kind),timeline:()=>get('/api/v1/timeline','timeline'),glossary:()=>get('/api/v1/glossary','glossary'),map:()=>fallback('mapNodes'),daily:async()=>{if(base){try{return normalizeDaily(await json(base+'/api/v1/daily-feature'))}catch(error){console.warn('[Hogwarts Indonesia] daily fallback',error.message)}}return fallback('dailyFeatures')},search:async(params={})=>{if(base){try{return await json(base+'/api/v1/search?'+new URLSearchParams(params))}catch(error){console.warn('[Hogwarts Indonesia] search fallback',error.message)}}return localSearch({...params,type:'article'})},searchAll:localSearch};
}
