import {search} from './search.js';
const main=document.querySelector('main');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=k=>{try{const a=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(a)?a.filter(x=>typeof x==='string'):[]}catch{return[]}};
let timer;function notice(t){document.querySelector('#notice').textContent=t;clearTimeout(timer);timer=setTimeout(()=>document.querySelector('#notice').textContent='',4000)}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{notice('Penyimpanan perangkat tidak tersedia.');return false}}
let data;
function cards(items){return items.length?'<div class="cards">'+items.map(a=>'<section class="card"><span class="eyebrow">'+esc(data.categories.find(c=>c.slug===a.category)?.title)+'</span><h3><a href="#/artikel/'+esc(a.slug)+'">'+esc(a.title)+'</a></h3><p>'+esc(a.intro)+'</p></section>').join('')+'</div>':'<p class="empty">Tidak ada artikel dalam pilihan ini. <a href="#/index">Jelajahi perpustakaan</a>.</p>'}
function route(){const raw=location.hash.slice(1)||'/';const [path,query]=raw.split('?');const params=new URLSearchParams(query);const slug=path.split('/')[2];const cat=data.categories.find(c=>'/'+c.slug===path);let title='Perpustakaan Dunia Sihir';
if(path==='/'){main.innerHTML='<section class="hero"><p class="eyebrow">Arsip dunia sihir · Bahasa Indonesia</p><h1>Setiap pintu,<br>sebuah pengetahuan.</h1><p>Ikuti lorong cerita, temukan tokoh di balik peristiwa, dan buka kembali halaman dunia sihir.</p><a class="button" href="#/index">Masuki perpustakaan →</a></section><p class="eyebrow">Dua belas ruang pengetahuan</p><h2>Pilih arah penjelajahanmu</h2><div class="collection-grid">'+data.categories.map(c=>'<a class="collection" href="#/'+c.slug+'"><span class="number">'+String(c.id).padStart(2,'0')+' / KOLEKSI</span><h3>'+esc(c.title)+'</h3><p>'+esc(c.subtitle)+' →</p></a>').join('')+'</div>'}
else if(path==='/index'||cat){title=cat?.title||'Perpustakaan';main.innerHTML='<p class="eyebrow">Indeks pengetahuan</p><h1>'+esc(title)+'</h1><form class="tools" id="search"><label class="field">Cari artikel<input name="q" type="search" value="'+esc(params.get('q')||'')+'" placeholder="Nama, tempat, atau gagasan"></label><label class="field">Koleksi<select name="category"><option value="">Semua koleksi</option>'+data.categories.map(c=>'<option value="'+c.slug+'" '+((cat?.slug||params.get('category'))===c.slug?'selected':'')+'>'+esc(c.title)+'</option>').join('')+'</select></label><button>Cari</button></form><p id="count" role="status"></p><div id="results"></div>';const form=main.querySelector('form');const update=()=>{const matches=search(data.articles,form.q.value,form.category.value);main.querySelector('#results').innerHTML=cards(matches);main.querySelector('#count').textContent=matches.length+' artikel';};form.addEventListener('input',update);form.addEventListener('submit',e=>{e.preventDefault();location.hash='/index?'+new URLSearchParams(new FormData(form)).toString()});update()}
else if(path.startsWith('/artikel/')){const a=data.articles.find(a=>a.slug===slug);if(!a){missing();return}title=a.title;const history=read('hi-history');save('hi-history',[slug,...history.filter(x=>x!==slug)].slice(0,100));main.innerHTML='<p class="crumb"><a href="#/index">Perpustakaan</a> / <a href="#/'+a.category+'">'+esc(data.categories.find(c=>c.slug===a.category)?.title)+'</a></p><article class="folio"><p class="eyebrow">Arsip Hogwarts Indonesia</p><h1>'+esc(a.title)+'</h1><p>'+esc(a.intro)+'</p>'+a.sections.map(s=>'<h2>'+esc(s.heading)+'</h2><p>'+esc(s.text)+'</p>').join('')+'<aside><h2>Catatan Penyihir</h2><p>'+esc(a.note)+'</p></aside><div class="tools"><button id="bookmark" aria-pressed="'+read('hi-bookmarks').includes(slug)+'">'+(read('hi-bookmarks').includes(slug)?'Hapus bookmark':'Simpan bookmark')+'</button><button id="share">Bagikan artikel</button></div><h2>Sumber bacaan</h2><p class="source">'+(a.source.url?'<a href="'+esc(a.source.url)+'" target="_blank" rel="noopener noreferrer">'+esc(a.source.title)+'</a>':esc(a.source.author+' — '+a.source.title+'; '+a.source.locator))+'<br>'+esc(a.source.verification)+'</p></article><h2>Baca berikutnya</h2>'+cards(data.articles.filter(x=>a.related.includes(x.slug)));main.querySelector('#bookmark').onclick=e=>{let b=read('hi-bookmarks'),on=!b.includes(slug);if(save('hi-bookmarks',on?[...b,slug]:b.filter(x=>x!==slug))){e.target.setAttribute('aria-pressed',on);e.target.textContent=on?'Hapus bookmark':'Simpan bookmark';notice(on?'Artikel disimpan di perangkat ini.':'Bookmark dihapus.')}};main.querySelector('#share').onclick=async()=>{try{if(navigator.share)await navigator.share({title:a.title,url:location.href});else{await navigator.clipboard.writeText(location.href);notice('Tautan disalin.')}}catch(e){if(e.name!=='AbortError')notice('Salin alamat artikel dari bilah alamat browser.')}}}
else if(path==='/bookmark'||path==='/riwayat'){const isHistory=path==='/riwayat';title=isHistory?'Jejak penjelajahan':'Halaman tersimpan';const ids=read(isHistory?'hi-history':'hi-bookmarks');main.innerHTML='<p class="eyebrow">Disimpan pada perangkat ini</p><h1>'+title+'</h1>'+cards(ids.map(id=>data.articles.find(a=>a.slug===id)).filter(Boolean))}
else if(path==='/sumber'){title='Sumber & catatan editorial';main.innerHTML='<h1>'+title+'</h1><p>Narasi disusun ulang dalam Bahasa Indonesia. Referensi buku menyebutkan bab; status pemeriksaan ditampilkan pada setiap artikel. Gambar resmi tidak disalin.</p>'+data.articles.map(a=>'<section class="card"><h2><a href="#/artikel/'+a.slug+'">'+esc(a.title)+'</a></h2><p>'+esc(a.source.title)+' — '+esc(a.source.verification)+'</p></section>').join('')}
else if(path==='/tentang'){title='Tentang arsip ini';main.innerHTML='<p class="eyebrow">Sebuah ruang baca independen</p><h1>Dunia yang luas.<br>Bahasa yang dekat.</h1><p>Hogwarts Indonesia menyajikan pembacaan ensiklopedis dunia sihir dalam Bahasa Indonesia. Nama ini adalah identitas antarmuka, bukan klaim adanya sekolah Hogwarts resmi di Indonesia.</p><h2>Fakta dan tafsir</h2><p>Informasi cerita dipisahkan dari interpretasi editorial. Catatan sumber membantu pembaca menelusuri kembali konteksnya.</p><h2>Privasi perangkat</h2><p>Bookmark dan riwayat disimpan lokal di browser. Tidak ada akun atau pelacak analitik pada versi ini.</p><button id="clear">Hapus bookmark dan riwayat perangkat</button>';main.querySelector('#clear').onclick=()=>{if(confirm('Hapus bookmark dan riwayat pada perangkat ini?')){save('hi-bookmarks',[]);save('hi-history',[]);notice('Data perangkat dihapus.')}}}
else {missing();return}
document.title=title+' — Hogwarts Indonesia';main.focus({preventScroll:true});scrollTo(0,0)}
function missing(){document.title='Halaman tidak ditemukan — Hogwarts Indonesia';main.innerHTML='<h1>Lorong ini tidak ditemukan.</h1><p>Alamat mungkin berubah. <a href="#/index">Kembali ke perpustakaan</a>.</p>';main.focus()}
try{const res=await fetch(new URL('../data/catalog.json',import.meta.url));if(!res.ok)throw Error('catalog');data=await res.json();route();addEventListener('hashchange',route);if('serviceWorker'in navigator)navigator.serviceWorker.register(new URL('../service-worker.js',import.meta.url)).catch(()=>{});}catch{main.innerHTML='<h1>Perpustakaan sedang kehilangan koneksi ke dunia Muggle.</h1><p>Katalog belum dapat dibuka. Periksa koneksi, lalu muat ulang.</p><button id="retry">Coba lagi</button>';main.querySelector('#retry').onclick=()=>location.reload()}
