import {esc,entityCards,statusBlock,articleCards,sectionHeading,sourceView} from './ui.js';

export async function renderEntity({main,api,kind,title,intro,finish,onRendered,relatedArticles=[],categories=[]}){
  main.innerHTML=`<div class="route-frame"><span class="eyebrow">Field Guide</span><h1>${esc(title)}</h1><p class="muted">${esc(intro)}</p><label class="field entity-filter">Cari dalam ${esc(title)}<input id="entity-filter" type="search" placeholder="Ketik nama atau istilah"></label><p id="entity-count" class="eyebrow" role="status"></p><div id="entity-results"><p>Memuat arsip…</p></div>${relatedArticles.length?sectionHeading('Artikel terkait','Pembacaan editorial')+articleCards(relatedArticles,categories):''}</div>`;finish(title);
  try{const res=await api.entities(kind),items=res.items||[],root=main.querySelector('#entity-results'),count=main.querySelector('#entity-count'),input=main.querySelector('#entity-filter');const update=()=>{const q=(input.value||'').trim().toLowerCase();const filtered=items.filter(x=>!q||[x.name,x.title,x.incantation,x.term,x.summary,x.description,x.purpose,x.habitat,x.classification,x.region].filter(Boolean).join(' ').toLowerCase().includes(q));count.textContent=`${filtered.length} entri`;root.innerHTML=entityCards(filtered,title);onRendered()};input.addEventListener('input',update);update()}catch{main.querySelector('#entity-results').innerHTML=statusBlock('error','Arsip belum dapat dibuka','Sumber data sedang tidak dapat dijangkau.')}
}

export async function renderMap({main,api,finish,onRendered}){
  main.innerHTML=`<div class="route-frame"><span class="eyebrow">Navigasi spasial editorial</span><h1>Peta Kastil</h1><p class="muted">Peta ini sengaja bersifat ilustratif. Ia membantu orientasi dalam aplikasi dan tidak mengklaim sebagai denah canon atau koordinat resmi.</p><div class="map-layout"><div class="map-panel" id="castle-map" aria-label="Peta interaktif kastil"><p class="map-loading">Membuka peta…</p></div><aside class="map-preview" id="map-preview" aria-live="polite"><span class="eyebrow">Pilih titik</span><h2>Jelajahi ruang</h2><p>Pilih salah satu penanda pada peta untuk membaca konteks sebelum berpindah ruang.</p></aside></div></div>`;finish('Peta Kastil');
  try{const response=await api.map(),nodes=response.items||[],map=main.querySelector('#castle-map'),preview=main.querySelector('#map-preview');if(!nodes.length){map.innerHTML=statusBlock('empty','Peta belum memiliki titik','Data navigasi spasial belum tersedia.');return}map.innerHTML=nodes.map((node,index)=>`<button class="map-pin" style="left:${Number(node.x)}%;top:${Number(node.y)}%" data-map-node="${esc(node.id)}" aria-label="Pratinjau ${esc(node.label)}">${index+1}<span>${esc(node.label)}</span></button>`).join('');const open=node=>{preview.innerHTML=`<span class="eyebrow">${esc(node.group||'Ruang')}</span><h2>${esc(node.label)}</h2><p>${esc(node.description||'')}</p><a class="button" href="#${esc(node.route||'/index')}">Masuk ke ruang →</a>`};map.addEventListener('click',event=>{const button=event.target.closest('[data-map-node]');if(!button)return;const node=nodes.find(x=>x.id===button.dataset.mapNode);if(node)open(node)});open(nodes[0]);onRendered()}catch{main.querySelector('#castle-map').innerHTML=statusBlock('error','Peta belum dapat dibuka','Data navigasi sedang tidak dapat dijangkau.')}
}

export async function renderTimeline({main,api,finish,onRendered}){
  main.innerHTML=`<div class="route-frame"><span class="eyebrow">Arsip waktu</span><h1>Timeline Dunia Sihir</h1><p class="muted">Peristiwa ditata sebagai urutan editorial. Tahun yang tidak pasti menggunakan label era agar aplikasi tidak mengarang tanggal.</p><div id="timeline"><p>Memuat timeline…</p></div></div>`;finish('Timeline');
  try{const res=await api.timeline(),items=res.items||[];main.querySelector('#timeline').innerHTML=items.length?`<div class="timeline">${items.map(e=>`<article class="timeline-item"><div class="timeline-year">${esc(e.year_label||e.year||e.era||'Era tidak pasti')}</div><h3>${esc(e.title||e.event)}</h3><p>${esc(e.summary||e.description||'')}</p>${e.source?sourceView(e.source):''}</article>`).join('')}</div>`:statusBlock('empty','Timeline sedang disusun','Belum ada record timeline pada sumber aktif.');onRendered()}catch{main.querySelector('#timeline').innerHTML=statusBlock('error','Timeline belum dapat dibuka','Coba lagi setelah koneksi data pulih.')}
}

export async function renderGlossary({main,api,finish,onRendered}){
  main.innerHTML=`<div class="route-frame"><span class="eyebrow">Indeks istilah</span><h1>Glosarium</h1><p class="muted">Penjelasan ringkas istilah kompleks agar pengalaman berbahasa Indonesia tetap mudah dipahami.</p><label class="field glossary-search">Cari istilah<input id="glossary-search" type="search" placeholder="Mis. Patronus, Animagus, Wizengamot"></label><p id="glossary-count" class="eyebrow" role="status"></p><div id="glossary"><p>Memuat glosarium…</p></div></div>`;finish('Glosarium');
  try{const res=await api.glossary(),items=res.items||[],root=main.querySelector('#glossary'),input=main.querySelector('#glossary-search'),count=main.querySelector('#glossary-count');const update=()=>{const q=(input.value||'').trim().toLowerCase();const filtered=items.filter(x=>!q||[x.term,x.definition,x.description,...(Array.isArray(x.aliases)?x.aliases:[])].filter(Boolean).join(' ').toLowerCase().includes(q));count.textContent=`${filtered.length} istilah`;root.innerHTML=filtered.length?`<dl class="glossary-list">${filtered.map(x=>`<div class="glossary-item"><dt>${esc(x.term)}</dt><dd>${esc(x.definition||x.description)}</dd></div>`).join('')}</dl>`:statusBlock('empty','Istilah tidak ditemukan','Coba kata kunci lain.');onRendered()};input.addEventListener('input',update);update()}catch{main.querySelector('#glossary').innerHTML=statusBlock('error','Glosarium belum dapat dibuka','Koneksi data sedang bermasalah.')}
}

export function renderGrimoireHub({main,articles,categories,finish}){
  const related=articles.filter(x=>x.category==='grimoire');main.innerHTML=`<div class="route-frame"><span class="eyebrow">Grimoire</span><h1>Mantra, Ramuan & Artefak</h1><p class="muted">Tiga indeks saling terhubung untuk membedakan fungsi sihir, ramuan fiksi, dan benda yang berperan dalam cerita.</p><div class="collection-grid mini-hubs"><a class="collection-card" href="#/grimoire/mantra"><span class="number">01 · INDEKS</span><h3>Mantra</h3><p>Pelafalan, fungsi, kategori, dan konteks.</p></a><a class="collection-card" href="#/grimoire/ramuan"><span class="number">02 · INDEKS</span><h3>Ramuan</h3><p>Arsip lore; bukan petunjuk praktik dunia nyata.</p></a><a class="collection-card" href="#/grimoire/artefak"><span class="number">03 · INDEKS</span><h3>Artefak</h3><p>Benda sihir dan hubungan dengan peristiwa.</p></a></div>${related.length?sectionHeading('Artikel editorial','Pembacaan mendalam')+articleCards(related,categories):''}</div>`;finish('Grimoire')
}
