import {esc,entityCards,statusBlock} from './ui.js';

export async function renderEntity({main,api,kind,title,intro,finish,onRendered}){main.innerHTML=`<div class="route-frame"><span class="eyebrow">Field Guide</span><h1>${esc(title)}</h1><p class="muted">${esc(intro)}</p><div id="entity-results"><p>Memuat arsip…</p></div></div>`;finish(title);try{const res=await api.entities(kind);main.querySelector('#entity-results').innerHTML=entityCards(res.items||[],title);onRendered()}catch{main.querySelector('#entity-results').innerHTML=statusBlock('error','Arsip belum dapat dibuka','Sumber data sedang tidak dapat dijangkau.')}}

export function renderMap({main,finish}){const pins=[['Great Hall',56,51,'/'],['Library',46,43,'/index'],['Astronomy Tower',55,25,'/astronomi'],['Greenhouses',25,57,'/herbologi'],['Dungeons',50,74,'/grimoire/ramuan'],['Courtyard',68,53,'/hogwarts'],['Forbidden Forest',82,46,'/makhluk'],['Quidditch Grounds',24,79,'/quidditch'],['Ministry portal',84,66,'/kementerian'],['Diagon Alley portal',75,78,'/lokasi']];main.innerHTML=`<div class="route-frame"><span class="eyebrow">Navigasi spasial editorial</span><h1>Peta Kastil</h1><p class="muted">Peta ini sengaja bersifat ilustratif. Ia membantu orientasi dalam aplikasi dan tidak mengklaim sebagai denah canon atau koordinat resmi.</p><div class="map-panel" aria-label="Peta interaktif kastil">${pins.map(([name,x,y,path],i)=>`<a class="map-pin" style="left:${x}%;top:${y}%" href="#${path}" aria-label="Buka ${esc(name)}">${i+1}<span>${esc(name)}</span></a>`).join('')}</div></div>`;finish('Peta Kastil')}

export async function renderTimeline({main,api,finish,onRendered}){main.innerHTML=`<div class="route-frame"><span class="eyebrow">Arsip waktu</span><h1>Timeline Dunia Sihir</h1><p class="muted">Peristiwa ditata sebagai urutan editorial. Tahun yang tidak pasti dapat menggunakan label era agar aplikasi tidak mengarang tanggal.</p><div id="timeline"><p>Memuat timeline…</p></div></div>`;finish('Timeline');try{const res=await api.timeline(),items=res.items||[];main.querySelector('#timeline').innerHTML=items.length?`<div class="timeline">${items.map(e=>`<article class="timeline-item"><div class="timeline-year">${esc(e.year_label||e.year||e.era||'Era tidak pasti')}</div><h3>${esc(e.title||e.event)}</h3><p>${esc(e.summary||e.description||'')}</p></article>`).join('')}</div>`:statusBlock('empty','Timeline sedang disusun','Belum ada record timeline pada sumber aktif.');onRendered()}catch{main.querySelector('#timeline').innerHTML=statusBlock('error','Timeline belum dapat dibuka','Coba lagi setelah koneksi data pulih.')}}

export async function renderGlossary({main,api,finish,onRendered}){main.innerHTML=`<div class="route-frame"><span class="eyebrow">Indeks istilah</span><h1>Glosarium</h1><p class="muted">Penjelasan ringkas istilah kompleks agar pengalaman berbahasa Indonesia tetap mudah dipahami.</p><div id="glossary"><p>Memuat glosarium…</p></div></div>`;finish('Glosarium');try{const res=await api.glossary(),items=res.items||[];main.querySelector('#glossary').innerHTML=items.length?`<dl class="glossary-list">${items.map(x=>`<div class="glossary-item"><dt>${esc(x.term)}</dt><dd>${esc(x.definition||x.description)}</dd></div>`).join('')}</dl>`:statusBlock('empty','Glosarium belum berisi record','Backend dapat menambahkan istilah melalui migration dan CMS.');onRendered()}catch{main.querySelector('#glossary').innerHTML=statusBlock('error','Glosarium belum dapat dibuka','Koneksi data sedang bermasalah.')}}
