import {esc,collectionCards,articleCards,searchResultCards,dailyFeatureCards,sectionHeading,sourceView} from './ui.js';
import {readList,toggleInList,pushRecent} from './state.js';

export async function renderHome({main,categories,articles,progress,api,finish,onRendered}){
  const featured=articles.slice(0,6);
  main.innerHTML=`<div class="route-frame"><section class="hero-castle" aria-labelledby="home-title"><div class="mist-layer"></div><div class="hero-copy"><span class="eyebrow">Ensiklopedia dunia sihir · Bahasa Indonesia</span><h1 id="home-title">Masuki kastil pengetahuan.</h1><p class="lede">Berjalan dari aula menuju perpustakaan, menara, rumah kaca, dungeon, dan arsip tersembunyi. Setiap ruang membuka hubungan baru antara tokoh, tempat, makhluk, mantra, dan peristiwa.</p><div class="hero-actions"><a class="button" href="#/index">Jelajahi perpustakaan →</a><a class="ghost-button" href="#/peta">Buka peta kastil</a></div></div><aside class="hero-statbar"><blockquote>Pengetahuan menjadi peta ketika setiap kisah terhubung dengan kisah lain.</blockquote><div class="stat-grid"><div><strong>${categories.length}</strong><span>Koleksi</span></div><div><strong>${articles.length}</strong><span>Artikel awal</span></div><div><strong>${progress}%</strong><span>Terjelajahi</span></div></div></aside></section>${sectionHeading('Great Hall','Dua belas pintu pengetahuan','#/index')}${collectionCards(categories)}<section id="daily-area" aria-live="polite"></section>${sectionHeading('Arsip pilihan','Mulai dari catatan yang telah diverifikasi','#/index')}${articleCards(featured,categories)}<section class="split" style="margin-top:3rem"><div><span class="eyebrow">Jalur alternatif</span><h2>Jelajahi berdasarkan ruang.</h2><p class="muted">Peta adalah navigasi editorial, bukan denah resmi. Timeline menata peristiwa, graph membantu melihat hubungan, sementara glosarium menjelaskan istilah kompleks.</p><div class="cluster"><a class="ghost-button" href="#/peta">Peta kastil</a><a class="ghost-button" href="#/timeline">Timeline</a><a class="ghost-button" href="#/relasi">Graph relasi</a><a class="ghost-button" href="#/glosarium">Glosarium</a></div></div><div class="wizard-note"><span class="eyebrow">Catatan editor</span><h3>Canon, sumber, dan tafsir dipisahkan.</h3><p>Artikel menandai fakta canon dan interpretasi editorial agar pembaca tidak perlu menebak mana informasi cerita dan mana pembacaan redaksi.</p></div></section></div>`;
  finish('Hogwarts Indonesia');
  try{const daily=await api.daily(),items=daily.items||[];if(items.length){const area=main.querySelector('#daily-area');area.innerHTML=sectionHeading('Hari ini','Empat catatan dari kastil')+dailyFeatureCards(items.slice(0,4));onRendered()}}catch(error){console.warn('[Hogwarts Indonesia] daily features unavailable',error.message)}
}

export function renderIndex({main,categories,articles,category,params,api,finish,onRendered}){
  const initialQ=params.get('q')||'',initialCategory=category?.slug||params.get('category')||'',initialType=params.get('type')||'';
  main.innerHTML=`<div class="route-frame"><span class="eyebrow">Restricted Section Index</span><h1>${esc(category?.title||'Perpustakaan')}</h1><p class="muted">Pencarian menjangkau artikel, tokoh, makhluk, mantra, ramuan, artefak, lokasi, astronomi, dan glosarium. Salah ketik sederhana ditoleransi pada mode katalog lokal.</p><form class="tools" id="library-search"><label class="field">Kata kunci<input name="q" type="search" value="${esc(initialQ)}" placeholder="Mis. Hogwarts, Patronus, Hogsmeade"></label><label class="field">Jenis<select name="type"><option value="">Semua jenis</option><option value="article" ${initialType==='article'?'selected':''}>Artikel</option><option value="character" ${initialType==='character'?'selected':''}>Tokoh</option><option value="creature" ${initialType==='creature'?'selected':''}>Makhluk</option><option value="spell" ${initialType==='spell'?'selected':''}>Mantra</option><option value="potion" ${initialType==='potion'?'selected':''}>Ramuan</option><option value="artifact" ${initialType==='artifact'?'selected':''}>Artefak</option><option value="location" ${initialType==='location'?'selected':''}>Lokasi</option><option value="astronomy" ${initialType==='astronomy'?'selected':''}>Astronomi</option><option value="glossary" ${initialType==='glossary'?'selected':''}>Glosarium</option></select></label><label class="field">Koleksi artikel<select name="category"><option value="">Semua koleksi</option>${categories.map(c=>`<option value="${esc(c.slug)}" ${initialCategory===c.slug?'selected':''}>${esc(c.title)}</option>`).join('')}</select></label><button class="button">Cari arsip</button></form><p id="count" class="eyebrow" role="status"></p><div id="results"></div></div>`;
  const form=main.querySelector('#library-search'),results=main.querySelector('#results'),count=main.querySelector('#count');let serial=0,timer;
  const update=async()=>{const id=++serial,q=form.q.value.trim(),type=form.type.value,cat=form.category.value;count.textContent='Menelusuri arsip…';try{if(category||(!q&&!type&&cat)){const list=articles.filter(a=>(!cat||a.category===cat)&&(!q||[a.title,a.intro,a.slug,a.category,...(a.sections||[]).map(s=>s.heading)].join(' ').toLowerCase().includes(q.toLowerCase())));if(id!==serial)return;count.textContent=`${list.length} artikel ditemukan`;results.innerHTML=articleCards(list,categories)}else if(!q&&!type&&!cat){if(id!==serial)return;count.textContent=`${articles.length} artikel tersedia`;results.innerHTML=articleCards(articles,categories)}else{const response=await api.searchAll({q,type,category:cat});if(id!==serial)return;const items=response.items||[];count.textContent=`${response.total??items.length} hasil ditemukan`;results.innerHTML=searchResultCards(items,q)}onRendered()}catch(error){if(id!==serial)return;count.textContent='Pencarian gagal';results.innerHTML='<div class="error-state"><h2>Indeks belum dapat dibuka.</h2><p>Coba lagi setelah koneksi data pulih.</p></div>'}};
  form.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(update,140)});form.addEventListener('submit',event=>{event.preventDefault();const query=new URLSearchParams(new FormData(form));for(const [key,value] of [...query])if(!value)query.delete(key);location.hash='/index'+(query.size?'?'+query:'')});update();finish(category?.title||'Perpustakaan');
}

export async function renderArticle({main,categories,articles,slug,api,finish,notice,onRendered,missing}){
  let a=articles.find(x=>x.slug===slug);if(!a)a=await api.contentBySlug(slug).catch(()=>null);if(!a)return missing();pushRecent(slug);const bookmarked=readList('bookmarks').includes(slug),c=categories.find(x=>x.slug===a.category);const currentIndex=articles.findIndex(x=>x.slug===slug),previous=currentIndex>0?articles[currentIndex-1]:null,next=currentIndex>=0&&currentIndex<articles.length-1?articles[currentIndex+1]:null;
  main.innerHTML=`<div class="route-frame"><div class="reading-progress" aria-hidden="true"><span id="reading-progress-bar"></span></div><p class="crumb"><a href="#/">Great Hall</a> / <a href="#/${esc(a.category)}">${esc(c?.title||a.category)}</a> / ${esc(a.title)}</p><div class="reading-layout"><article class="folio"><span class="eyebrow">${esc(a.canon||'Arsip Hogwarts Indonesia')}</span><h1>${esc(a.title)}</h1><p><strong>${esc(a.intro)}</strong></p>${(a.sections||[]).map((s,i)=>`${i===0?'<hr>':''}<h2>${esc(s.heading)}</h2><p>${esc(s.text)}</p>`).join('')}<aside><span class="eyebrow">Catatan Penyihir</span><p>${esc(a.note||'Catatan editorial belum tersedia.')}</p></aside><div class="tools"><button class="ghost-button" id="bookmark" aria-pressed="${bookmarked}">${bookmarked?'Hapus bookmark':'Simpan bookmark'}</button><button class="ghost-button" id="share">Bagikan</button></div></article><aside class="reading-aside stack"><div class="fact-box"><span class="eyebrow">Quick facts</span><dl><dt>Koleksi</dt><dd>${esc(c?.title||a.category)}</dd><dt>Status</dt><dd>${esc(a.status||'published')}</dd><dt>Provenance</dt><dd>${a.source?'Tersedia':'Perlu audit'}</dd></dl></div>${sourceView(a.source||{})}<div class="wizard-note"><span class="eyebrow">Navigasi</span><p><a href="#/${esc(a.category)}">Kembali ke koleksi</a></p><p><a href="#/sumber">Lihat daftar sumber</a></p></div></aside></div><nav class="article-pager" aria-label="Artikel sebelum dan sesudah">${previous?`<a href="#/artikel/${esc(previous.slug)}">← ${esc(previous.title)}</a>`:'<span></span>'}${next?`<a href="#/artikel/${esc(next.slug)}">${esc(next.title)} →</a>`:'<span></span>'}</nav>${sectionHeading('Relasi','Baca berikutnya')}${articleCards(articles.filter(x=>(a.related||[]).includes(x.slug)),categories)}</div>`;
  main.querySelector('#bookmark').addEventListener('click',e=>{const on=toggleInList('bookmarks',slug);e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=on?'Hapus bookmark':'Simpan bookmark';notice(on?'Artikel disimpan pada perangkat ini.':'Bookmark dihapus.')});main.querySelector('#share').addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:a.title,url:location.href});else{await navigator.clipboard.writeText(location.href);notice('Tautan artikel disalin.')}}catch(error){if(error.name!=='AbortError')notice('Salin alamat artikel dari bilah alamat browser.')}});
  const bar=main.querySelector('#reading-progress-bar'),updateProgress=()=>{if(!bar)return;const max=document.documentElement.scrollHeight-innerHeight;bar.style.transform=`scaleX(${max>0?Math.min(1,scrollY/max):0})`};addEventListener('scroll',updateProgress,{passive:true});window.__hiRouteCleanup=()=>removeEventListener('scroll',updateProgress);updateProgress();finish(a.title);onRendered();
}
