import {esc,entityCards,statusBlock,articleCards,sectionHeading,sourceView,highlightText} from './ui.js';

const detailBaseForKind={characters:'/tokoh',creatures:'/makhluk',spells:'/grimoire/mantra',potions:'/grimoire/ramuan',artifacts:'/grimoire/artefak',plants:'/herbologi',locations:'/lokasi',astronomy:'/astronomi'};
const detailFacts=item=>[
  ['Asrama',item.house],['Afiliasi',item.affiliation],['Klasifikasi',item.classification],['Habitat',item.habitat],['Tingkat risiko',item.danger_level],['Pelafalan',item.incantation],['Jenis',item.type],['Kesulitan',item.difficulty],['Status legal',item.legal_status],['Wilayah',item.region],['Status canon',item.canon_status]
].filter(([,value])=>value);
const hueFor=value=>[...String(value||'Hogwarts')].reduce((sum,c)=>(sum+c.charCodeAt(0))%360,36);

export async function renderEntity({main,api,kind,title,intro,params=new URLSearchParams(),finish,onRendered,relatedArticles=[],categories=[]}){
  const initialQ=params.get('q')||'',detailBase=detailBaseForKind[kind]||'';
  main.innerHTML=`<div class="route-frame"><span class="eyebrow">Field Guide</span><h1>${esc(title)}</h1><p class="muted">${esc(intro)}</p><label class="field entity-filter">Cari dalam ${esc(title)}<input id="entity-filter" type="search" value="${esc(initialQ)}" placeholder="Ketik nama atau istilah"></label><p id="entity-count" class="eyebrow" role="status"></p><div id="entity-source"></div><div id="entity-results"><p>Memuat arsip…</p></div>${relatedArticles.length?sectionHeading('Artikel terkait','Pembacaan editorial')+articleCards(relatedArticles,categories):''}</div>`;finish(title);
  try{const res=await api.entities(kind),items=res.items||[],root=main.querySelector('#entity-results'),count=main.querySelector('#entity-count'),input=main.querySelector('#entity-filter'),sourceRoot=main.querySelector('#entity-source');if(res.sources?.[0])sourceRoot.innerHTML=`<div class="field-guide-source">${sourceView(res.sources[0])}<p class="muted">Sumber ini adalah provenance tingkat batch. Tautan item per entri tetap diperkaya bertahap melalui CMS.</p></div>`;const update=()=>{const raw=(input.value||'').trim(),q=raw.toLowerCase();const filtered=items.filter(x=>!q||[x.name,x.title,x.incantation,x.term,x.summary,x.description,x.purpose,x.habitat,x.classification,x.region,x.house,x.affiliation,x.difficulty,x.legal_status,x.danger_level].filter(Boolean).join(' ').toLowerCase().includes(q));count.textContent=`${filtered.length} dari ${items.length} entri`;root.innerHTML=entityCards(filtered,title,detailBase,raw);onRendered()};input.addEventListener('input',()=>{const query=input.value.trim();const current=(location.hash.slice(1).split('?')[0]||'/');history.replaceState(null,'',location.pathname+location.search+'#'+current+(query?'?q='+encodeURIComponent(query):''));update()});update()}catch{main.querySelector('#entity-results').innerHTML=statusBlock('error','Arsip belum dapat dibuka','Sumber data sedang tidak dapat dijangkau.')}
}

export async function renderEntityDetail({main,api,kind,slug,sectionTitle,baseRoute,finish,onRendered,missing}){
  main.innerHTML=`<div class="route-frame"><p class="crumb"><a href="#/">Great Hall</a> / <a href="#${esc(baseRoute)}">${esc(sectionTitle)}</a> / Membuka arsip…</p><div class="entity-detail-loading"><p>Menarik catatan dari perpustakaan…</p></div></div>`;
  try{
    const response=await api.entityBySlug(kind,slug);if(!response?.item)return missing();const item=response.item,source=response.source||item.source||null,label=item.name||item.title||item.term||slug,summary=item.summary||item.description||item.purpose||item.definition||'',facts=detailFacts(item),hue=hueFor(slug),sourceIsBatch=source?.level==='batch-index'||item.metadata?.provenanceLevel==='batch-index';
    main.innerHTML=`<div class="route-frame"><p class="crumb"><a href="#/">Great Hall</a> / <a href="#${esc(baseRoute)}">${esc(sectionTitle)}</a> / ${esc(label)}</p><section class="entity-detail-hero" style="--entity-hue:${hue}" aria-labelledby="entity-detail-title"><div><span class="eyebrow">${esc(item.classification||item.type||item.house||sectionTitle)}</span><h1 id="entity-detail-title">${esc(label)}</h1><p class="lede">${esc(summary)}</p></div><div class="entity-sigil" aria-hidden="true">${esc(label.slice(0,1).toUpperCase())}</div></section><div class="reading-layout entity-detail-layout"><article class="folio entity-folio"><span class="eyebrow">Catatan ensiklopedis</span><h2>Ringkasan</h2><p>${esc(summary)}</p>${item.purpose&&item.purpose!==summary?`<h2>Fungsi dalam lore</h2><p>${esc(item.purpose)}</p>`:''}${item.safety_note?`<aside><span class="eyebrow">Catatan keselamatan</span><p>${esc(item.safety_note)}</p></aside>`:''}<aside><span class="eyebrow">Catatan Penyihir</span><p>Halaman ini menyajikan ringkasan transformatif. Detail faktual yang lebih panjang akan ditambahkan ketika provenance item-level telah diverifikasi oleh workflow editorial.</p></aside></article><aside class="reading-aside stack"><div class="fact-box"><span class="eyebrow">Quick facts</span>${facts.length?`<dl>${facts.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`:'<p class="muted">Metadata tambahan belum tersedia.</p>'}</div>${source?sourceView(source):`<div class="source-drawer"><span class="eyebrow">Provenance</span><h3>Perlu enrichment</h3><p class="source">Belum ada source record yang dapat ditampilkan untuk entri ini.</p></div>`}${sourceIsBatch?`<div class="wizard-note"><span class="eyebrow">Status sumber</span><p>Provenance saat ini berada pada tingkat indeks batch. Direct source per entri tetap menjadi pekerjaan editorial berikutnya.</p></div>`:''}<div class="wizard-note"><span class="eyebrow">Jalur eksplorasi</span><p><a href="#${esc(baseRoute)}">← Kembali ke ${esc(sectionTitle)}</a></p><p><a href="#/index?q=${encodeURIComponent(label)}">Cari relasi di seluruh arsip</a></p><p><a href="#/relasi">Buka graph relasi</a></p><p><a href="#/timeline">Buka timeline</a></p></div></aside></div></div>`;
    finish(label);onRendered();
  }catch(error){console.error('[Hogwarts Indonesia] entity detail failed',error);main.innerHTML=statusBlock('error','Arsip detail belum dapat dibuka','Sumber data sedang tidak dapat dijangkau.');finish(sectionTitle)}
}

export async function renderMap({main,api,finish,onRendered}){
  main.innerHTML=`<div class="route-frame"><span class="eyebrow">Navigasi spasial editorial</span><h1>Peta Kastil</h1><p class="muted">Peta ini sengaja bersifat ilustratif. Ia membantu orientasi dalam aplikasi dan tidak mengklaim sebagai denah canon atau koordinat resmi.</p><div class="map-layout"><div class="map-panel" id="castle-map" aria-label="Peta interaktif kastil"><p class="map-loading">Membuka peta…</p></div><aside class="map-preview" id="map-preview" aria-live="polite"><span class="eyebrow">Pilih titik</span><h2>Jelajahi ruang</h2><p>Pilih salah satu penanda pada peta untuk membaca konteks sebelum berpindah ruang.</p></aside></div></div>`;finish('Peta Kastil');
  try{const response=await api.map(),nodes=response.items||[],map=main.querySelector('#castle-map'),preview=main.querySelector('#map-preview');if(!nodes.length){map.innerHTML=statusBlock('empty','Peta belum memiliki titik','Data navigasi spasial belum tersedia.');return}map.innerHTML=nodes.map((node,index)=>`<button class="map-pin" style="left:${Number(node.x)}%;top:${Number(node.y)}%" data-map-node="${esc(node.id)}" aria-label="Pratinjau ${esc(node.label)}">${index+1}<span>${esc(node.label)}</span></button>`).join('');const open=node=>{preview.innerHTML=`<span class="eyebrow">${esc(node.group||'Ruang')}</span><h2>${esc(node.label)}</h2><p>${esc(node.description||'')}</p><a class="button" href="#${esc(node.route||'/index')}">Masuk ke ruang →</a>`};map.addEventListener('click',event=>{const button=event.target.closest('[data-map-node]');if(!button)return;const node=nodes.find(x=>x.id===button.dataset.mapNode);if(node)open(node)});open(nodes[0]);onRendered()}catch{main.querySelector('#castle-map').innerHTML=statusBlock('error','Peta belum dapat dibuka','Data navigasi sedang tidak dapat dijangkau.')}
}

export async function renderTimeline({main,api,finish,onRendered}){
  main.innerHTML=`<div class="route-frame"><span class="eyebrow">Arsip waktu</span><h1>Timeline Dunia Sihir</h1><p class="muted">Peristiwa ditata sebagai urutan editorial. Tahun yang tidak pasti menggunakan label era agar aplikasi tidak mengarang tanggal.</p><div id="timeline"><p>Memuat timeline…</p></div></div>`;finish('Timeline');
  try{const res=await api.timeline(),items=res.items||[];main.querySelector('#timeline').innerHTML=items.length?`<div class="timeline">${items.map(e=>`<article class="timeline-item"><div class="timeline-year">${esc(e.year_label||e.year||e.era||'Era tidak pasti')}</div><h3>${esc(e.title||e.event)}</h3><p>${esc(e.summary||e.description||'')}</p>${e.location_name?`<p class="timeline-context"><strong>Lokasi:</strong> ${esc(e.location_name)}</p>`:''}${e.source?sourceView(e.source):''}</article>`).join('')}</div>`:statusBlock('empty','Timeline sedang disusun','Belum ada record timeline pada sumber aktif.');onRendered()}catch{main.querySelector('#timeline').innerHTML=statusBlock('error','Timeline belum dapat dibuka','Coba lagi setelah koneksi data pulih.')}
}

export async function renderGlossary({main,api,params=new URLSearchParams(),finish,onRendered}){
  const initialQ=params.get('q')||'';
  main.innerHTML=`<div class="route-frame"><span class="eyebrow">Indeks istilah</span><h1>Glosarium</h1><p class="muted">Penjelasan ringkas istilah kompleks agar pengalaman berbahasa Indonesia tetap mudah dipahami.</p><label class="field glossary-search">Cari istilah<input id="glossary-search" type="search" value="${esc(initialQ)}" placeholder="Mis. Patronus, Animagus, Wizengamot"></label><p id="glossary-count" class="eyebrow" role="status"></p><div id="glossary"><p>Memuat glosarium…</p></div></div>`;finish('Glosarium');
  try{const res=await api.glossary(),items=res.items||[],root=main.querySelector('#glossary'),input=main.querySelector('#glossary-search'),count=main.querySelector('#glossary-count');const update=()=>{const raw=(input.value||'').trim(),q=raw.toLowerCase();const filtered=items.filter(x=>!q||[x.term,x.definition,x.description,...(Array.isArray(x.aliases)?x.aliases:[])].filter(Boolean).join(' ').toLowerCase().includes(q));count.textContent=`${filtered.length} dari ${items.length} istilah`;root.innerHTML=filtered.length?`<dl class="glossary-list">${filtered.map(x=>`<div class="glossary-item"><dt>${highlightText(x.term,raw)}</dt><dd>${highlightText(x.definition||x.description,raw)}</dd></div>`).join('')}</dl>`:statusBlock('empty','Istilah tidak ditemukan','Coba kata kunci lain.');onRendered()};input.addEventListener('input',()=>{const query=input.value.trim();history.replaceState(null,'',location.pathname+location.search+'#/glosarium'+(query?'?q='+encodeURIComponent(query):''));update()});update()}catch{main.querySelector('#glossary').innerHTML=statusBlock('error','Glosarium belum dapat dibuka','Koneksi data sedang bermasalah.')}
}

export function renderGrimoireHub({main,articles,categories,finish}){
  const related=articles.filter(x=>x.category==='grimoire');main.innerHTML=`<div class="route-frame"><span class="eyebrow">Grimoire</span><h1>Mantra, Ramuan & Artefak</h1><p class="muted">Tiga indeks saling terhubung untuk membedakan fungsi sihir, ramuan fiksi, dan benda yang berperan dalam cerita.</p><div class="collection-grid mini-hubs"><a class="collection-card" href="#/grimoire/mantra"><span class="number">01 · INDEKS</span><h3>Mantra</h3><p>Pelafalan, fungsi, kategori, kesulitan, dan status legal.</p></a><a class="collection-card" href="#/grimoire/ramuan"><span class="number">02 · INDEKS</span><h3>Ramuan</h3><p>Arsip lore; bukan petunjuk praktik dunia nyata.</p></a><a class="collection-card" href="#/grimoire/artefak"><span class="number">03 · INDEKS</span><h3>Artefak</h3><p>Benda sihir dan hubungan dengan peristiwa.</p></a></div>${related.length?sectionHeading('Artikel editorial','Pembacaan mendalam')+articleCards(related,categories):''}</div>`;finish('Grimoire')
}
