const PREF_KEY='hi:shell-settings';
const readSettings=()=>{try{return JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch{return{}}};
const writeSettings=value=>{try{localStorage.setItem(PREF_KEY,JSON.stringify(value))}catch{}};
function applySettings(settings){document.documentElement.dataset.motion=settings.motion==='reduce'?'reduce':'system';document.documentElement.style.fontSize=`${Math.round((Number(settings.textScale)||1)*100)}%`}
function installSettings(){const settings={motion:'system',textScale:1,...readSettings()};applySettings(settings);const dialog=document.querySelector('#settings-panel'),toggle=document.querySelector('[data-settings-toggle]');if(!dialog||!toggle)return;const motion=dialog.querySelector('[name="motion"]'),scale=dialog.querySelector('[name="textScale"]'),output=dialog.querySelector('output');motion.value=settings.motion;scale.value=String(settings.textScale);output.value=Math.round(settings.textScale*100)+'%';toggle.addEventListener('click',()=>dialog.showModal());dialog.querySelector('[data-close-settings]')?.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});dialog.addEventListener('input',()=>{settings.motion=motion.value;settings.textScale=Number(scale.value);output.value=Math.round(settings.textScale*100)+'%';applySettings(settings);writeSettings(settings)})}
const sceneFor=path=>{const root=(path.split('/')[1]||'great-hall').toLowerCase();if(path.startsWith('/grimoire'))return'grimoire';if(path.startsWith('/artikel/'))return'article';if(path.startsWith('/tokoh/'))return'tokoh';if(path.startsWith('/makhluk/'))return'makhluk';if(path.startsWith('/lokasi/'))return'lokasi';if(path.startsWith('/herbologi/'))return'herbologi';if(path.startsWith('/astronomi/'))return'astronomi';if(['graph','relasi'].includes(root))return'relasi';if(['bookmark','riwayat'].includes(root))return'personal';if(['sumber','kredit-aset','tentang'].includes(root))return'archive';return root.replace(/[^a-z0-9-]/g,'')||'great-hall'};
function installRouteAtmosphere(){const sync=()=>{const raw=location.hash.slice(1)||'/';const path=raw.split('?')[0];document.documentElement.dataset.scene=sceneFor(path);document.documentElement.dataset.route=path.slice(1).replace(/[^a-z0-9-]/gi,'-')||'home'};sync();addEventListener('hashchange',sync)}
export function upgradeShell(){
  const styles=['tokens.css','base.css','layout.css','components.css','graph.css','animations.css','responsive.css','deep-dive.css','premium-castle.css','premium-scenes.css'];
  for(const file of styles){if(!document.querySelector(`link[href$="${file}"]`)){const link=document.createElement('link');link.rel='stylesheet';link.href=new URL(`../css/${file}`,import.meta.url);document.head.append(link)}}
  document.querySelector('link[href$="app.css"]')?.remove();
  let meta=document.querySelector('meta[name="api-base"]');if(!meta){meta=document.createElement('meta');meta.name='api-base';meta.content='';document.head.append(meta)}
  const header=document.querySelector('header');if(header){header.className='site-header';header.innerHTML=`<a class="brand" href="#/" aria-label="Hogwarts Indonesia — Beranda"><span class="brand-mark" aria-hidden="true">HI</span><span class="brand-copy">HOGWARTS<small>INDONESIA</small></span></a><form class="header-search" id="global-search-form" role="search"><label class="visually-hidden" for="global-search">Cari seluruh ensiklopedia</label><input id="global-search" name="q" type="search" autocomplete="off" placeholder="Telusuri arsip kastil…"><kbd>/</kbd></form><nav class="top-nav" aria-label="Navigasi utama"><a href="#/">Great Hall</a><a href="#/index">Koleksi</a><a href="#/peta">Peta</a><a href="#/timeline">Timeline</a><a href="#/relasi">Relasi</a><a href="#/glosarium">Glosarium</a><a href="#/bookmark">Bookmark</a><button class="nav-button" type="button" data-settings-toggle aria-label="Pengaturan tampilan">Pengaturan</button></nav>`}
  const main=document.querySelector('main');if(main){main.className='main-stage';if(!main.parentElement?.classList.contains('app-shell')){const wrap=document.createElement('div');wrap.className='app-shell';main.before(wrap);wrap.append(main)}}
  const oldNotice=document.querySelector('#notice');if(oldNotice)oldNotice.className='notice';
  const footer=document.querySelector('footer');if(footer){footer.className='site-footer';footer.innerHTML=`<div class="site-footer-inner"><div><a class="brand" href="#/"><span class="brand-mark" aria-hidden="true">HI</span><span class="brand-copy">HOGWARTS<small>INDONESIA</small></span></a><p class="muted">Arsip pengetahuan dunia sihir dalam Bahasa Indonesia.</p></div><div><div class="footer-links"><a href="#/sumber">Sumber</a><a href="#/kredit-aset">Kredit aset</a><a href="#/tentang">Tentang</a><a href="#/riwayat">Riwayat</a><a href="./admin.html">Editorial Console</a></div><p>Hogwarts Indonesia adalah proyek ensiklopedis/fan-made independen berbahasa Indonesia dan tidak berafiliasi dengan Warner Bros. Discovery, J.K. Rowling, Wizarding World, atau pemegang hak terkait.</p></div></div>`}
  if(!document.querySelector('#loading-gate')){const gate=document.createElement('div');gate.id='loading-gate';gate.className='loading-gate';gate.hidden=true;gate.innerHTML=`<div class="gate-card"><div class="gate-seal" aria-hidden="true">HI</div><span class="eyebrow">Arsip malam · Gerbang utama</span><h1>Hogwarts Indonesia</h1><p>Masuki ensiklopedia kastil yang disusun sebagai perjalanan editorial. Visualnya original, audio tetap senyap secara default, dan gerak mengikuti preferensi perangkat.</p><div class="gate-actions"><button class="button" data-enter>Masuki Kastil</button><button class="ghost-button" data-skip>Lewati pembuka</button></div></div>`;document.body.prepend(gate)}
  if(!document.querySelector('#settings-panel')){const dialog=document.createElement('dialog');dialog.id='settings-panel';dialog.dataset.modal='';dialog.className='settings-dialog';dialog.innerHTML=`<form method="dialog" class="settings-card"><div class="settings-head"><div><span class="eyebrow">Preferensi pembaca</span><h2>Pengaturan tampilan</h2></div><button class="icon-button" type="button" data-close-settings aria-label="Tutup pengaturan">×</button></div><label class="field">Gerak dan animasi<select name="motion"><option value="system">Ikuti perangkat</option><option value="reduce">Kurangi gerak</option></select></label><label class="field">Skala teks<div class="range-row"><input name="textScale" type="range" min="1" max="1.3" step="0.05"><output>100%</output></div></label><p class="muted">Preferensi disimpan hanya pada browser ini. Audio tidak pernah diputar otomatis.</p></form>`;document.body.append(dialog)}
  installRouteAtmosphere();installSettings();
}
