export function upgradeShell(){
  const styles=['tokens.css','base.css','layout.css','components.css','graph.css','animations.css','responsive.css'];
  for(const file of styles){if(!document.querySelector(`link[href$="${file}"]`)){const link=document.createElement('link');link.rel='stylesheet';link.href=new URL(`../css/${file}`,import.meta.url);document.head.append(link)}}
  document.querySelector('link[href$="app.css"]')?.remove();
  let meta=document.querySelector('meta[name="api-base"]');if(!meta){meta=document.createElement('meta');meta.name='api-base';meta.content='';document.head.append(meta)}
  const header=document.querySelector('header');if(header){header.className='site-header';header.innerHTML=`<a class="brand" href="#/" aria-label="Hogwarts Indonesia — Beranda"><span class="brand-mark" aria-hidden="true">HI</span><span class="brand-copy">HOGWARTS<small>INDONESIA</small></span></a><form class="header-search" id="global-search-form" role="search"><label class="visually-hidden" for="global-search">Cari seluruh ensiklopedia</label><input id="global-search" name="q" type="search" autocomplete="off" placeholder="Cari artikel, tokoh, lokasi, atau istilah…"><kbd>/</kbd></form><nav class="top-nav" aria-label="Navigasi utama"><a href="#/">Beranda</a><a href="#/index">Koleksi</a><a href="#/peta">Peta</a><a href="#/timeline">Timeline</a><a href="#/relasi">Relasi</a><a href="#/glosarium">Glosarium</a><a href="#/bookmark">Bookmark</a><a href="#/tentang">Tentang</a></nav>`}
  const main=document.querySelector('main');if(main){main.className='main-stage';if(!main.parentElement?.classList.contains('app-shell')){const wrap=document.createElement('div');wrap.className='app-shell';main.before(wrap);wrap.append(main)}}
  const oldNotice=document.querySelector('#notice');if(oldNotice)oldNotice.className='notice';
  const footer=document.querySelector('footer');if(footer){footer.className='site-footer';footer.innerHTML=`<div class="site-footer-inner"><div><a class="brand" href="#/"><span class="brand-mark" aria-hidden="true">HI</span><span class="brand-copy">HOGWARTS<small>INDONESIA</small></span></a></div><div><div class="footer-links"><a href="#/sumber">Sumber</a><a href="#/kredit-aset">Kredit aset</a><a href="#/tentang">Tentang</a><a href="#/riwayat">Riwayat</a></div><p>Proyek ensiklopedis fan-made independen berbahasa Indonesia; tidak berafiliasi dengan pemegang hak terkait.</p></div></div>`}
  if(!document.querySelector('#loading-gate')){const gate=document.createElement('div');gate.id='loading-gate';gate.className='loading-gate';gate.hidden=true;gate.innerHTML=`<div class="gate-card"><div class="gate-seal" aria-hidden="true">HI</div><span class="eyebrow">Perjalanan dimulai di gerbang</span><h1>Hogwarts Indonesia</h1><p>Ensiklopedia fan-made independen dalam Bahasa Indonesia. Audio tidak diputar otomatis dan gerak mengikuti pengaturan perangkat.</p><div class="gate-actions"><button class="button" data-enter>Masuki Kastil</button><button class="ghost-button" data-skip>Lewati pembuka</button></div></div>`;document.body.prepend(gate)}
}
