export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const routeLink=(path,label,cls='')=>`<a${cls?` class="${esc(cls)}"`:''} href="#${esc(path)}">${label}</a>`;
const palettes=[['#16263a','#6d461f'],['#172a22','#56411c'],['#1e2431','#6e0f19'],['#1b2932','#234c3e'],['#241c2c','#5c2d54'],['#1d2a24','#6c5522'],['#2c1e26','#213e34'],['#122538','#5e481e'],['#1f2a31','#593721'],['#252137','#6f4723'],['#162536','#3d4d64'],['#231d31','#5b3c20']];
const typeLabel={article:'Artikel',character:'Tokoh',creature:'Makhluk',spell:'Mantra',potion:'Ramuan',artifact:'Artefak',location:'Lokasi',glossary:'Glosarium'};
export function collectionCards(categories){return `<div class="collection-grid">${categories.map((c,i)=>{const p=palettes[i%palettes.length];return `<a class="collection-card reveal" style="--collection-art:linear-gradient(145deg,${p[0]},${p[1]})" href="#/${esc(c.slug)}"><span class="number">${String(c.id).padStart(2,'0')} · KOLEKSI</span><h3>${esc(c.title)}</h3><p>${esc(c.subtitle||'Buka arsip')}</p></a>`}).join('')}</div>`}
export function articleCards(items,categories=[]){if(!items?.length)return `<div class="empty-state"><span class="eyebrow">Arsip sunyi</span><h2>Belum ada catatan pada pilihan ini.</h2><p>Coba ubah pencarian atau kembali ke indeks utama.</p><a class="button" href="#/index">Buka indeks</a></div>`;return `<div class="cards">${items.map(a=>{const c=categories.find(x=>x.slug===a.category);return `<article class="card reveal"><span class="eyebrow">${esc(c?.title||a.category||'Artikel')}</span><h3><a href="#/artikel/${esc(a.slug)}">${esc(a.title)}</a></h3><p>${esc(a.intro||'')}</p><div class="meta"><span>${esc(a.canon||'Catatan editorial')}</span><span>→ Baca arsip</span></div></article>`}).join('')}</div>`}
export function entityCards(items,kind,route=''){if(!items?.length)return `<p class="muted">Data ${esc(kind)} belum tersedia pada sumber aktif.</p>`;return `<div class="entity-grid">${items.map(x=>`<article class="entity-card reveal"><span class="badge">${esc(x.classification||x.type||x.house||kind)}</span><h3>${route?`<a href="#${esc(route)}?q=${encodeURIComponent(x.name||x.title||'')}">${esc(x.name||x.title)}</a>`:esc(x.name||x.title)}</h3><p>${esc(x.summary||x.description||x.purpose||x.habitat||'')}</p></article>`).join('')}</div>`}
export function searchResultCards(items=[]){if(!items.length)return `<div class="empty-state"><span class="eyebrow">Tidak ditemukan</span><h2>Tidak ada hasil yang cocok.</h2><p>Coba istilah lain atau kurangi filter.</p></div>`;return `<div class="cards search-results">${items.map(item=>`<article class="card reveal"><span class="badge">${esc(typeLabel[item.entityType]||item.entityType||'Arsip')}</span><h3><a href="#${esc(item.route||'/index')}">${esc(item.label||item.title||item.name||item.term)}</a></h3><p>${esc(item.description||item.intro||item.summary||item.definition||'')}</p><div class="meta"><span>${item.slug?esc(item.slug):'Hogwarts Indonesia'}</span><span>→ Buka</span></div></article>`).join('')}</div>`}
export function dailyFeatureCards(items=[]){if(!items.length)return '';return `<div class="daily-grid">${items.map(x=>`<a class="daily-card reveal" href="#${esc(x.route||'/index')}"><span class="eyebrow">${esc(typeLabel[x.type]||x.type||'Hari ini')}</span><h3>${esc(x.title)}</h3><p>${esc(x.summary||'')}</p></a>`).join('')}</div>`}
export function sectionHeading(kicker,title,link=''){return `<div class="section-heading"><div><span class="eyebrow">${esc(kicker)}</span><h2>${esc(title)}</h2></div>${link?`<a href="${esc(link)}">Lihat semua →</a>`:''}</div>`}
export function statusBlock(type,title,text,action=''){const cls=type==='offline'?'offline-state':type==='error'?'error-state':'empty-state';return `<div class="${cls}"><span class="eyebrow">${type==='offline'?'Koneksi terputus':'Catatan kastil'}</span><h1>${esc(title)}</h1><p>${esc(text)}</p>${action}</div>`}
export function sourceView(source={}){const label=source.title||source.publisher||'Sumber';return `<div class="source-drawer"><span class="eyebrow">Provenance</span><h3>${esc(label)}</h3><p class="source">${source.url?`<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">Buka sumber</a><br>`:''}${esc([source.author,source.publisher,source.locator].filter(Boolean).join(' · '))}${source.verification?`<br>${esc(source.verification)}`:''}${source.accessedAt?`<br>Diakses ${esc(source.accessedAt)}`:''}</p></div>`}
